FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build

RUN go get -u github.com/SergeyStrashko/design-practice-2/build/cmd/bood

WORKDIR /go/src/practice-3
COPY . .

RUN mv build.bood build/product/ && mv build/test/build.bood . && CGO_ENABLED=0
ENTRYPOINT ["bood"]
